{
 "title": "Jetty Javalin",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jetty Threads Inventory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "jetty.threads.current.application.InventoryService"
    },
    {
     "target": "jetty.threads.config.*.application.InventoryService"
    }
   ]
  },
  {
   "title": "Jetty Threads Product",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "jetty.threads.current.application.ProductService"
    },
    {
     "target": "jetty.threads.config.*.application.ProductService"
    }
   ]
  },
  {
   "title": "Jetty Connections Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "jetty.connections.current.application.*"
    }
   ]
  },
  {
   "title": "Jetty Threads Busy and Idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "jetty.threads.busy.application.*"
    }
   ]
  },
  {
   "title": "API Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "derivative(seriesByTag('name=jetty.server.requests.exception.Unknown.method.GET.outcome.SUCCESS.status.200.uri./future', 'metricattribute=count'))"
    },
    {
     "target": "derivative(seriesByTag('name=jetty.server.requests.application.ProductService.exception.Unknown.method.GET.outcome.SUCCESS.status.200.uri./product/:id', 'metricattribute=count'))"
    },
    {
     "target": "derivative(seriesByTag('name=jetty.server.requests.application.InventoryService.exception.Unknown.method.GET.outcome.SUCCESS.status.200.uri./inventory/:locationId/decorateProduct', 'metricattribute=count'))"
    }
   ]
  },
  {
   "title": "API Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "stats_counts.response.500" },
    { "target": "stats_counts.response.404" }
   ]
  },
  {
   "title": "Product GET latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "seriesByTag('name=jetty.server.requests.application.ProductService.exception.Unknown.method.GET.outcome.SUCCESS.status.200.uri./product/:id', 'metricattribute=p99')"
    },
    {
     "target": "seriesByTag('name=jetty.server.requests.application.ProductService.exception.Unknown.method.GET.outcome.SUCCESS.status.200.uri./product/:id', 'metricattribute=max')"
    },
    {
     "target": "seriesByTag('name=jetty.server.requests.application.ProductService.exception.Unknown.method.GET.outcome.SUCCESS.status.200.uri./product/:id', 'metricattribute=p95')"
    }
   ]
  }
 ]
}